// GENERATED by scripts/gen-species-registry.py — do not edit. Lists every JSON under species/.
import type { ArchTemplate, GenusDef, SpeciesSheet } from './resolve.js';

import tpl_champagnat from '../../../../species/templates/champagnat.json' with { type: 'json' };
import tpl_massart from '../../../../species/templates/massart.json' with { type: 'json' };
import tpl_rauh from '../../../../species/templates/rauh.json' with { type: 'json' };
import tpl_troll from '../../../../species/templates/troll.json' with { type: 'json' };
import gen_acer from '../../../../species/genera/acer.json' with { type: 'json' };
import gen_betula from '../../../../species/genera/betula.json' with { type: 'json' };
import gen_fagus from '../../../../species/genera/fagus.json' with { type: 'json' };
import gen_fraxinus from '../../../../species/genera/fraxinus.json' with { type: 'json' };
import gen_picea from '../../../../species/genera/picea.json' with { type: 'json' };
import gen_pinus from '../../../../species/genera/pinus.json' with { type: 'json' };
import gen_platanus from '../../../../species/genera/platanus.json' with { type: 'json' };
import gen_populus from '../../../../species/genera/populus.json' with { type: 'json' };
import gen_prunus from '../../../../species/genera/prunus.json' with { type: 'json' };
import gen_quercus from '../../../../species/genera/quercus.json' with { type: 'json' };
import gen_salix from '../../../../species/genera/salix.json' with { type: 'json' };
import gen_tilia from '../../../../species/genera/tilia.json' with { type: 'json' };
import sp_acer_platanoides from '../../../../species/acer-platanoides.json' with { type: 'json' };
import sp_betula_pendula from '../../../../species/betula-pendula.json' with { type: 'json' };
import sp_fagus_sylvatica from '../../../../species/fagus-sylvatica.json' with { type: 'json' };
import sp_fraxinus_excelsior from '../../../../species/fraxinus-excelsior.json' with { type: 'json' };
import sp_picea_abies from '../../../../species/picea-abies.json' with { type: 'json' };
import sp_pinus_sylvestris from '../../../../species/pinus-sylvestris.json' with { type: 'json' };
import sp_platanus_acerifolia from '../../../../species/platanus-acerifolia.json' with { type: 'json' };
import sp_populus_tremula from '../../../../species/populus-tremula.json' with { type: 'json' };
import sp_prunus_avium from '../../../../species/prunus-avium.json' with { type: 'json' };
import sp_quercus_robur from '../../../../species/quercus-robur.json' with { type: 'json' };
import sp_salix_babylonica from '../../../../species/salix-babylonica.json' with { type: 'json' };
import sp_tilia_cordata from '../../../../species/tilia-cordata.json' with { type: 'json' };

export const TEMPLATES: ArchTemplate[] = [tpl_champagnat as unknown as ArchTemplate, tpl_massart as unknown as ArchTemplate, tpl_rauh as unknown as ArchTemplate, tpl_troll as unknown as ArchTemplate];
export const GENERA: GenusDef[] = [gen_acer as unknown as GenusDef, gen_betula as unknown as GenusDef, gen_fagus as unknown as GenusDef, gen_fraxinus as unknown as GenusDef, gen_picea as unknown as GenusDef, gen_pinus as unknown as GenusDef, gen_platanus as unknown as GenusDef, gen_populus as unknown as GenusDef, gen_prunus as unknown as GenusDef, gen_quercus as unknown as GenusDef, gen_salix as unknown as GenusDef, gen_tilia as unknown as GenusDef];
export const SHEETS: SpeciesSheet[] = [sp_acer_platanoides as unknown as SpeciesSheet, sp_betula_pendula as unknown as SpeciesSheet, sp_fagus_sylvatica as unknown as SpeciesSheet, sp_fraxinus_excelsior as unknown as SpeciesSheet, sp_picea_abies as unknown as SpeciesSheet, sp_pinus_sylvestris as unknown as SpeciesSheet, sp_platanus_acerifolia as unknown as SpeciesSheet, sp_populus_tremula as unknown as SpeciesSheet, sp_prunus_avium as unknown as SpeciesSheet, sp_quercus_robur as unknown as SpeciesSheet, sp_salix_babylonica as unknown as SpeciesSheet, sp_tilia_cordata as unknown as SpeciesSheet];
