#!/usr/bin/env python3
"""Regenerate packages/core/src/species/registry.generated.ts from the JSON files under species/."""
import os
here=os.path.dirname(os.path.abspath(__file__)); core=os.path.join(here,'..'); root=os.path.join(core,'..','..','species')
def ident(s): return s.replace('-','_')
lines=["// GENERATED by scripts/gen-species-registry.py — do not edit. Lists every JSON under species/.",
       "import type { ArchTemplate, GenusDef, SpeciesSheet } from './resolve.js';",""]
t=sorted(f[:-5] for f in os.listdir(os.path.join(root,'templates')) if f.endswith('.json'))
g=sorted(f[:-5] for f in os.listdir(os.path.join(root,'genera')) if f.endswith('.json'))
s=sorted(f[:-5] for f in os.listdir(root) if f.endswith('.json'))
for x in t: lines.append(f"import tpl_{ident(x)} from '../../../../species/templates/{x}.json' with {{ type: 'json' }};")
for x in g: lines.append(f"import gen_{ident(x)} from '../../../../species/genera/{x}.json' with {{ type: 'json' }};")
for x in s: lines.append(f"import sp_{ident(x)} from '../../../../species/{x}.json' with {{ type: 'json' }};")
lines.append("")
lines.append("export const TEMPLATES: ArchTemplate[] = [" + ", ".join(f"tpl_{ident(x)} as unknown as ArchTemplate" for x in t) + "];")
lines.append("export const GENERA: GenusDef[] = [" + ", ".join(f"gen_{ident(x)} as unknown as GenusDef" for x in g) + "];")
lines.append("export const SHEETS: SpeciesSheet[] = [" + ", ".join(f"sp_{ident(x)} as unknown as SpeciesSheet" for x in s) + "];")
open(os.path.join(core,'src','species','registry.generated.ts'),'w').write("\n".join(lines)+"\n")
print(f"registry: {len(t)} templates, {len(g)} genera, {len(s)} species")
