export * from './types.js';
export { Rng, hash01 } from './rng.js';
export { TreeGrowth, insideObstacle } from './growth/grow.js';
export type { GrowthOptions } from './growth/grow.js';
export { MarkerField, generateMarkers, insideEnvelope } from './growth/markers.js';
export { ShadowGrid } from './growth/shadow.js';
export { phenologyAt, dailyTemperature, gddToDay, leafColor } from './growth/phenology.js';
export { buildBranchMesh } from './mesh/branches.js';
export type { BranchMeshOptions } from './mesh/branches.js';
export { buildLeaves, LEAF_CLUSTER_SIZE } from './mesh/leaves.js';
export { simplifySkeleton } from './mesh/simplify.js';
export { SPECIES, SPECIES_IDS, getSpecies, applyOverrides } from './species/index.js';
export { generate, defaultIndividual, PlantSession } from './generate.js';
export type { GenerateOptions } from './generate.js';
export { leafSilhouette, resolveLeafShape, leafFamilyOf, polygonArea, LEAF_FAMILY_DEFAULTS } from './organs/leafShape.js';
export type { LeafFamily, LeafShapeParams, LeafSilhouette, Vein } from './organs/leafShape.js';
